### ISSUE TITLE
Poetry lock giving runtime error

### ISSUE THREAD

**Issue by Mona19** [GoogleCloudPlatform/Open_Data_QnA#50]
I am trying to setup this solution in Cloud shell. When I run poetry lock it give 
RuntimeError

The Poetry configuration is invalid:
  - Additional properties are not allowed (u'group' was unexpected)

**Comment by orpzs** [comment]
The issue is with the Cloud Shell pip install poetry command installs the peotry compatible to 2.7 Python i.e. poetry 1.1.15.

Poetry 1.1.15 doesn't work with group dependencies and also the resolution requires an upgraded version of Poetry (as latest as possible)

Work around you can use

- Add the python3 site packages folder to the beginning of the PATH. This will force the system to look for Python3 packages only (e.g. export PATH="/home/admin_/.local/lib/python3.10/site-packages/poetry/bin:$PATH")
- Instead of pip install use pip3 install poetry to install poetry in the site python3 folder
- Uninstall poetry if already installed using pip so that only Python3 compatible poetry is present

NOTE: This workaround is strictly for cloud shell or for the cases where there is a conflicting/multiple Python Versions installed
